# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_issue_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='mod_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
