# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 23:57
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_issue_mod_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('artist', 'Artist'), ('colorist', 'Colorist'), ('cover', 'Cover'), ('editor', 'Editor'), ('inker', 'Inker'), ('journalist', 'Journalist'), ('letterer', 'Letterer'), ('other', 'Other'), ('penciler', 'Penciler'), ('production', 'Production'), ('writer', 'Writer'), ('penciller', 'Penciller')], max_length=97),
        ),
    ]
