# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_issue_mod_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='cvid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='cvid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cvid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cvid',
            field=models.PositiveIntegerField(unique=True, verbose_name='ComicVine ID'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='cvid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='cvid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='cvid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
