# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0014_cvid_to_int'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='settings',
            name='comics_directory',
            field=models.CharField(blank=True, help_text='Directory where comic archives are located.', max_length=350, verbose_name='Comics Directory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='file',
            field=models.CharField(max_length=300, verbose_name='File path'),
        ),
    ]
