# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0016_series_sort_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['sort_title'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='sort_title',
            field=models.CharField(max_length=200, verbose_name='Sort Name'),
        ),
    ]
