# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0017_use_series_sort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='cvid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='cvid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cvid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='cvid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]